### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by zhentg** [forlilab/waterkit#1]
Dear developer

cd autogrid
autoreconf -i
mkdir x86_64Linux2 # for x86_64architecture
cd x86_64Linux2
../configure
make

After the above commands, compilation of autogrid stops with error
make: *** No rule to make target '../../autodock/paramdat2h.csh', needed by 'default_parameters.h'.  Stop.

Could you help on this?

Zhenting

**Comment by jeeberhardt** [comment]
Hi @zhentg,

Sorry for the inconvenience, it looks like I didn't try compiling `autogrid` after putting it on GitHub.
Unfortunately, I am traveling right now and don't have access to my workstation. I will come back to you as soon as possible (either with a temporary fix or a permanent one)!

**Comment by MKCarter** [comment]
You can void the need to use the source code foir autogrid by installing it via conda:

`conda install -c bioconda autogrid`

Should give you a working `autogrid4` installation

**Comment by jeeberhardt** [comment]
Hi @MKCarter,

Nope, you can't. WaterKit uses a modified version of autogrid, with Amber FF atom types. The number of atom types is rather restricted to a limited number in the vanilla version of autogrid. This version expands the number to 56.

**Comment by jeeberhardt** [comment]
Hi @zhentg,

A new version is up, you can now compile `autogrid4`. Tell me if it works for you!

Best,

**Comment by MKCarter** [comment]
> Hi @MKCarter,
> 
> Nope, you can't. WaterKit uses a modified version of autogrid, with Amber FF atom types. The number of atom types is rather restricted to a limited number in the vanilla version of autogrid. This version expands the number to 56.

Ah I see... thanks for letting me know. Your fresh install instructions, work for me also. Thanks

**Comment by zhentg** [comment]
Hi @jeeberhardt ,

Sorry for the late response. 
After downloading the latest code,  I executed the following commands for compilation

> cd autodocksuite-4.2.6-src/autogrid;
> autoreconf -i;
> mkdir x86_64Linux2 # for x86_64architecture;
> cd x86_64Linux2;
> ../configure;
> make;
> make install; #(optional)

I used a non-root account for the installation, and met the following errors. I think the default location of autogrid should be changed accordingly to solve it. How to?

> make[1]: Leaving directory '/tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/x86_64Linux2'
> make  install-am
> make[1]: Entering directory '/tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/x86_64Linux2'
> make[2]: Entering directory '/tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/x86_64Linux2'
>  /usr/bin/mkdir -p '/usr/local/bin'
>   /usr/bin/install -c autogrid4 '/usr/local/bin'
> /usr/bin/install: cannot create regular file '/usr/local/bin/autogrid4': Permission denied
> make[2]: *** [Makefile:475: install-binPROGRAMS] Error 1
> make[2]: Leaving directory '/tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/x86_64Linux2'
> make[1]: *** [Makefile:1075: install-am] Error 2
> make[1]: Leaving directory '/tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/x86_64Linux2'
> make: *** [Makefile:1069: install] Error 2
>

**Comment by zhentg** [comment]
'make install' is optional. I skipped it and autogrid is compiled successfully.

**Comment by zhentg** [comment]
@jeeberhardt 

While executing configure, there is a warning about the script 'missing', is it important?

> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> /tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/missing: Unknown '--is-lightweight' option
> Try '/tools/solvation/waterkit-master/autodocksuite-4.2.6-src/autogrid/missing --help' for more information
> configure: WARNING: 'missing' script is too old or missing
