### ISSUE TITLE
documentation on output files from waterkit

### ISSUE THREAD

**Issue by blakemertz** [forlilab/waterkit#17]
After getting waterkit to successfully complete on a sample protein, the following files are produced:
```
gist-Esw-dens.dx
gist-Eww-dens.dx
gist-dTStrans-dens.dx
gist-dTSorient-dens.dx
gist-dTSsix-dens.dx
gist-neighbor-norm.dx
gist-dipole-dens.dx
gist-order-norm.dx
gist-dipolex-dens.dx
gist-dipoley-dens.dx
gist-dipolez-dens.dx
gist-gO.dx
gist-output.dat
gist-gH.dx
hydration.py
hydration_sites_dG_smoothed.pdb
gist-dG-dens_smoothed.dx
```
I know how to load and visualize the pdb/dx files, but I was wondering if there is any documentation describing each of the dx files, or if there is none, could it be provided?

**Comment by diogomart** [comment]
it's in the GIST documentation: https://amberhub.chpc.utah.edu/gist/

**Comment by blakemertz** [comment]
@diogomart thanks!
