### ISSUE TITLE
wk_prepare_receptor.py failed

### ISSUE THREAD

**Issue by zhentg** [forlilab/waterkit#3]
> python ../scripts/wk_prepare_receptor.py -i 7u9y_pro.pdb -o 7u9y_pro_prep --pdb --amber_pdbqt
> Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
> INFO:WaterKit receptor preparation:Removed all hydrogen atoms
> INFO:WaterKit receptor preparation:Removed all water molecules
> Traceback (most recent call last):
>   File "/tools/solvation/waterkit-master/test/../scripts/wk_prepare_receptor.py", line 854, in <module>
>     main()
>   File "/tools/solvation/waterkit-master/test/../scripts/wk_prepare_receptor.py", line 838, in main
>     pr.prepare(pdb_filename, lib_files, frcmod_files, clean)
>   File "/tools/solvation/waterkit-master/test/../scripts/wk_prepare_receptor.py", line 655, in prepare
>     ns_names = _find_non_standard_resnames(pdbfixer.parm, AMBER_SUPPORTED_RESNAMES + nonstandard_resnames)
> TypeError: can only concatenate tuple (not "list") to tuple

[7u9y_pro.zip](https://github.com/forlilab/waterkit/files/10095820/7u9y_pro.zip)

**Comment by jeeberhardt** [comment]
Hi @zhentg,

Sorry, last minute untested modifications... it is now fixed!

**Comment by zhentg** [comment]
Hi @jeeberhardt ,

Thanks for the bug fix.
After update whole waterkit directory, now the output seems correct.
Is it necessary to correct the 'simtk.openmm' importing statement?

> Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
> INFO:WaterKit receptor preparation:Removed all hydrogen atoms
> INFO:WaterKit receptor preparation:Removed all water molecules
> WARNING:WaterKit receptor preparation:Histidine protonation will be automatically assigned to HIE: HIS - 44, HIS - 86, HIS - 128, HIS - 170, HIS - 178, HIS - 255, HIS - 300, HIS - 310
