### ISSUE TITLE
How to calculate the dG, dH, dS and density all the hydration sites?

### ISSUE THREAD

**Issue by zhentg** [forlilab/waterkit#8]
Dear developers,

How to calculate the dG, dH, dS and density all the hydration sites?
With the script on Waterkit homepage, only dG is calculated.
https://github.com/forlilab/waterkit#identification-of-hydration-sites

Best 
Zhenting

**Comment by jeeberhardt** [comment]
Hi Zhenting,

It is quite easy actually! Just replace the `dg` variable by the map you want (either `esw`, `eww`, ...).

Here an example for the `esw` map:
```
# Get Gaussian smoothed energy for hydration sites only
esw_energy = hs.hydration_sites_energy(esw, water_radius=1.4)
hs.export_to_pdb("hydration_sites_dEsw_smoothed.pdb", hydration_sites, esw_energy)
```

Best,
Jerome.

**Comment by zhentg** [comment]
Thanks for the example. I have successfully calculation the dH and -TdS now.
